// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh6q5m_YEJVsOubsExZTYcfQaA0FJN1R8',
    appId: '1:1091858873953:web:4a0c41d59be7ed3aeb3420',
    messagingSenderId: '1091858873953',
    projectId: 'burgershop-43d6b',
    authDomain: 'burgershop-43d6b.firebaseapp.com',
    storageBucket: 'burgershop-43d6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgWu2-6MOggRSAbfUEO_8xIw1vGqfIi8',
    appId: '1:1091858873953:android:54fc90b0e44d5569eb3420',
    messagingSenderId: '1091858873953',
    projectId: 'burgershop-43d6b',
    storageBucket: 'burgershop-43d6b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDyGHXlkqpGXev4lHRtIOHJ_I1zZ2gN0c',
    appId: '1:1091858873953:ios:546e4744854b1412eb3420',
    messagingSenderId: '1091858873953',
    projectId: 'burgershop-43d6b',
    storageBucket: 'burgershop-43d6b.firebasestorage.app',
    iosClientId: '1091858873953-i40a1hhsmu1iokg4pa1h4foclkj9i32u.apps.googleusercontent.com',
    iosBundleId: 'com.example.burgershop',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDyGHXlkqpGXev4lHRtIOHJ_I1zZ2gN0c',
    appId: '1:1091858873953:ios:546e4744854b1412eb3420',
    messagingSenderId: '1091858873953',
    projectId: 'burgershop-43d6b',
    storageBucket: 'burgershop-43d6b.firebasestorage.app',
    iosClientId: '1091858873953-i40a1hhsmu1iokg4pa1h4foclkj9i32u.apps.googleusercontent.com',
    iosBundleId: 'com.example.burgershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh6q5m_YEJVsOubsExZTYcfQaA0FJN1R8',
    appId: '1:1091858873953:web:76ef8074359f6ba3eb3420',
    messagingSenderId: '1091858873953',
    projectId: 'burgershop-43d6b',
    authDomain: 'burgershop-43d6b.firebaseapp.com',
    storageBucket: 'burgershop-43d6b.firebasestorage.app',
  );
}
